# Generated by Django 2.1.7 on 2019-03-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='group', max_length=32)),
                ('rcount', models.IntegerField(default='3')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='robot', max_length=32)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('port', models.IntegerField(default='9999')),
            ],
        ),
        migrations.CreateModel(
            name='RobotGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('group', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Group')),
                ('robot', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Robot')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='robots',
            field=models.ManyToManyField(through='chat.RobotGroup', to='chat.Robot'),
        ),
    ]
